### ISSUE TITLE
no color，just black and white.

### ISSUE THREAD

**Issue by avfounder** [oxygine/oxygine-movie#2]
as title.

**Comment by frankinshtein** [comment]
need more info. Screenshots, description.

**Comment by pgranato** [comment]
I'm having the same problem on linux.
I've checked out the branch ox-move (as the master doesn't work with the current oxygine-framework).
The project builds correctly but the movies are shown in black and white

![screenshot from 2018-04-17 14-31-47](https://user-images.githubusercontent.com/12046295/38869895-857fb5c2-424c-11e8-87d5-f11ecbd35994.png)

![screenshot from 2018-04-17 14-32-40](https://user-images.githubusercontent.com/12046295/38870026-db7c96a2-424c-11e8-8d6f-ca720823a82d.png)

**Comment by frankinshtein** [comment]
fixed
